### ISSUE TITLE
Interface Task 4 - Facebook Login Page (Strictly using CSS-Flexbox)

### ISSUE THREAD

**Issue by zerefwayne** [opencodeiiita/sassy-css#52]
The hello-world for learning proper CSS UI designing.

![image](https://user-images.githubusercontent.com/28949397/51686909-5857da80-2017-11e9-8f1a-6f6354e6d285.png)

Search for any flexbox tutorials on youtube, and try to implement Flexbox. Doesn't matter if it takes 2-3 days to get used to Flexbox commands. You won't be able to forget the ease and sassyness flexbox provides while positioning elements.

**Comment by vishnuk7** [comment]
@opencodebot claim

**Comment by anupm12** [comment]
@opencodebot claim

**Comment by ujjwal-batra** [comment]
@opencodebot claim

**Comment by ujjwal-batra** [comment]
@opencodebot claim

**Comment by thesmallstar** [comment]
@zerefwayne  is this not for everyone?

**Comment by zerefwayne** [comment]
This is for everyone.

On 26-Jan-2019 15:04, "Manthan Surkar" <notifications@github.com> wrote:

@zerefwayne <https://github.com/zerefwayne> is this not for everyone?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/opencodeiiita/sassy-css/issues/52#issuecomment-457816968>,
or mute the thread

**Comment by vishnuk7** [comment]
@zerefwayne can I work on this?

**Comment by zerefwayne** [comment]
This is for everyone. Just make sure to implement it with flexbox.

On 29-Jan-2019 13:07, "Vishnu K Raman" <notifications@github.com> wrote:

@zerefwayne <https://github.com/zerefwayne> can I work on this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/opencodeiiita/sassy-css/issues/52#issuecomment-458437344>,
or mute the thread

**Comment by vishnuk7** [comment]
@zerefwayne @aswinzz @ananya-agrawal @pradeepgangwar @prateek76 
I just noticed that @Rattlecode17sh copied exactly my code for this issue.
All he has changed is the header color and an image and deleted few lines of SASS in the beginning.
You can just go checkout the name of classes, each and every class name is same and the whole code is same.
Also, to his bad he mistakenly referenced my pr in his pr and that is how I got to know about this.
Now this  itself makes it clear that there is something fishy, why would he open my pr if he is writing his own code?
This is seriously unfair @Rattlecode17sh .
This is a fair competition, I mean why would you do this?

I want all the mentors to have a look at this. This is violation of the code of conduct and some serious action should be taken.

Expecting immediate response.

My pr #61 
@Rattlecode17sh pr #63 

I have attached the screenshots below

![2](https://user-images.githubusercontent.com/31013847/52131970-2d4b3780-2664-11e9-9763-f6c2685f7c54.jpg)
![3](https://user-images.githubusercontent.com/31013847/52132020-4653e880-2664-11e9-8f3f-287e46136ed8.jpg)
![4](https://user-images.githubusercontent.com/31013847/52132021-4653e880-2664-11e9-8f38-5b2b31e78065.jpg)

**Comment by Rattlecode17sh** [comment]
I am sorry for the inconvenience. Clos my PR

**Comment by Rattlecode17sh** [comment]
You can reduce my points if you want to this is a serious mistake and i understand that. I will definitely not do it again in future

@zerefwayne , @vishnuk7 , @pradeepgangwar sorry for this kind of behaviour
